### ISSUE TITLE
Event handler code

### ISSUE THREAD

**Issue by poltak** [timotiousPrime/RocketLauncher#10]
- add listeners to the DOM for user interaction
- listeners should trigger correct state mutations

**Comment by timotiousPrime** [comment]
Can I close this issue?

**Comment by poltak** [comment]
There's still the hooking them up to the state. I might do that soon

**Comment by poltak** [comment]
Unless you want to. It's just following that idea of putting them in some setup function I put on slack, then calling the right mutations
