### ISSUE TITLE
Misc. sound effects

### ISSUE THREAD

**Issue by poltak** [timotiousPrime/RocketLauncher#44]
We need very short sound effect clips for things like :
- button presses
- falling obj catch
- life lost
- level up (rocket take off sound?)
- game over :( (explosion sound?)
- falling obj spawn

**Comment by timotiousPrime** [comment]
I'll have a look for these this weekend. I have the explosion sounds already

**Comment by timotiousPrime** [comment]
Misc sound effects added

**Comment by timotiousPrime** [comment]
One thing I noticed is that when it's game over, it still shows one life left
